# Generated by Django 3.1.2 on 2021-06-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kisumu', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
