# Generated by Django 3.1.2 on 2021-07-23 17:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kisumu', '0005_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='BlogImage'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='cause_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='CauseImage'),
        ),
    ]
